sudo: required

services:
  - docker

script:
  - docker build -t srechallenge .
  
deploy:
  provider: script
  script:
    - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
    - docker tag srechallenge srechallenge/srechallenge:latest 
    - docker push srechallenge/srechallenge:latest
    
  on:
    branch: master
