sudo: required

services:
  - docker

script:
  - docker build -t srechallenge .
  - docker run -it srechallenge go test 
  
after_success:
  - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  - docker tag srechallenge srechallenge/srechallenge:latest 
  - docker push srechallenge/srechallenge:latest
