sudo: required

services:
  - docker

script:
  - docker build -t srechallenge .

after_script:
  - docker images

befor_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  provider: script
  script: docker push srechallenge/srechallenge
  on:
    branch: master
